

create database ql_chuyenbay
GO
--Câu 1: Tạo các Quan hệ kèm khóa chính với dữ liệu được mô tả
drop database ql_chuyenbay
CREATE TABLE CHUYENBAY(
	MACB CHAR(5),
	NOIXP CHAR(15),
	NOIDEN CHAR(15),
	MAPHICO CHAR(5),
	TIENCONGCB MONEY,
	PRIMARY KEY (MACB)
);
CREATE TABLE PHICO(
	MAPHICO CHAR(5),
	TENPHICO CHAR(25),
	KCBAY INT,
	PRIMARY KEY (MAPHICO)
);
CREATE TABLE PHICONG (
	MAPHICONG CHAR(5),
	TENPHICONG CHAR (25),
	LUONG MONEY,
	SOLUONGCB INT,
	PRIMARY KEY (MAPHICONG)
);
CREATE TABLE LICHBAY(
	MAPHICONG CHAR(5),
	MACB CHAR(5),
	NGAYBAY SMALLDATETIME,
	PRIMARY KEY (MAPHICONG)
);

--Bảng tùy chọn
CREATE TABLE EMLAPHI(
	PHI CHAR(3),
	MSSV CHAR(4),
	21522453 CHAR(8),
	MMCL1 CHAR(5),
	PRIMARY KEY (MSSV),
);

--Tạo ràng buộc 
ALTER TABLE CHUYENBAY
ADD CONSTRAINT fk_cb_pco FOREIGN KEY	(MAPHICO) REFERENCES PHICO(MAPHICO)

ALTER TABLE LICHBAY
ADD CONSTRAINT fk_lb_pcong FOREIGN KEY	(MAPHICO) REFERENCES PHICO(MAPHICO)

ALTER TABLE LICHBAY
ADD CONSTRAINT fk_lb_cb FOREIGN KEY (MACB) REFERENCES CHUYENBAY(MACB)

-- 2.1
ALTER TABLE PHICO ADD CONSTRAINT CHECK_PhiCo CHECK(TENPHICO IN ('Airbus', 'Boeing','BAC'))
-- 2.2
ALTER TABLE CHUYENBAY ADD CONSTRAINT CHECK_ChuyenBay CHECK (NoiXP <> NoiDEN)
-- 2.3
-- 2.3
CREATE TRIGGER PHICONG_CB 
ON CHUYENBAY 
FOR INSERT,UPDATE
AS 
BEGIN
    DECLARE @MACB CHAR(5)
    SELECT @MACB = MACB FROM inserted
    IF(EXISTS(SELECT * FROM LICHBAY LBX, INSERTED WHERE LBX.MACB = @MACB AND EXISTS (SELECT * FROM PHICONG WHERE LBX.MAPHICONG = PHICONG.MAPHICONG AND SOLUONGCB > 100)))
        
            UPDATE CHUYENBAY SET TIENCONGCB = 10000000 WHERE CHUYENBAY.MaCB = @MACB
        
END


--Câu 3:
--3.1:
SELECT MACB
FROM CHUYENBAY
WHERE NOIDEN = 'HANOI' 
UNION
SELECT MACB
FROM CHUYENBAY
WHERE NOIDEN = 'HCM'

--3.2:
SELECT TENPHICO, TENPHICONG
FROM PHICO, PHICONG
GROUP BY MAPHICO
HAVING SUM (KCBAY) >= ALL(SELECT SUM(KCBAY) FROM PHICO GROUP BY MAPHICO)


--3.3
SELECT YEAR(NGAYBAY),NoiDEN 
FROM LICHBAY LBX, CHUYENBAY 
WHERE LBX.MACB = CHUYENBAY.MaCB AND EXISTS (
    SELECT SOLUONGCB FROM PHICONG GROUP BY SOLUONGCB HAVING PHICONG.MAPHICONG = LBX.MAPHICONG AND SOLUONGCB = MAX(SOLUONGCB)
)

-- 3.4
SELECT MAPHICONG,TENPHICONG 
FROM PHICONG 
WHERE LUONG > 100000000 
ORDER BY SOLUONGCB DESC

--3.5
SELECT NGAYBAY 
FROM LICHBAY, PHICONG 
WHERE LICHBAY.MAPHICONG = PHICONG.MAPHICONG
    GROUP BY NGAYBAY HAVING COUNT(PHICONG.MAPHICONG) >= COUNT(LICHBAY.MACB)